This is makeindex, version 2.17 [TeX Live 2025] (kpathsea + Thai support).
Scanning style file ./eblock418_user_manual.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file eblock418_user_manual.acn....done (15 entries accepted, 0 rejected).
Sorting entries....done (60 comparisons).
Generating output file eblock418_user_manual.acr....done (32 lines written, 0 warnings).
Output written in eblock418_user_manual.acr.
Transcript written in eblock418_user_manual.alg.
